######################################################################
# Automatically generated by qmake (2.01a) Thu May 6 06:19:38 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT -= declarative gui
DEFINES += NO_DECLARATIVE

# Input
HEADERS += ../common/tournament.h ../common/match.h
SOURCES += cgiMain.cpp ../common/tournament.cpp ../common/match.cpp
